apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookmanager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bookmanager.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookmanager
                port:
                  number: 80
