replicaCount: 1

image:
  repository: lukasneuberger01/bookmanager
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: bookmanager.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "walking-skeleton-lukas-5590.c.aivencloud.com"
  DB_PORT: 13267
  DB_NAME: "bookmanager"
  DB_USER: "avnadmin"
  DATABASE_TYPE: "postgresql"
  BOOK_API_URL: "https://openlibrary.org/api/books"

nodeSelector: {}

tolerations: []

affinity: {}
